name: pr
on:
  pull_request:
    branches:
      - v2

env:
  PRIVATE_KEY_MUMBAI: ${{ secrets.PRIVATE_KEY_MUMBAI }}
  PRIVATE_KEY_OASIS: ${{ secrets.PRIVATE_KEY_OASIS }}
  PRIVATE_KEY_ARBITRUM_NITRO: ${{ secrets.PRIVATE_KEY_ARBITRUM_NITRO }}

concurrency: pr

jobs:
  sanity_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm install -g npm@8.3.1
      - run: npm -v

      - run: npm install

      - run: npm run deploy:mumbai
      # - run: npm run deploy:emerald-test
      # - run: npm run deploy:arbitrum-nitro

      - run: npm run build

      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./app
          alias-domains: steps-app-dev.vercel.app
