name: pr
on:
  pull_request:
    branches:
      - main

env:
  PRIVATE_KEY_MUMBAI: ${{ secrets.PRIVATE_KEY_MUMBAI }}
  PRIVATE_KEY_OASIS: ${{ secrets.PRIVATE_KEY_OASIS }}

concurrency: pr

jobs:
  sanity_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 15
          cache: 'npm'

      - run: npm install
        working-directory: ./hardhat

      - run: npm run test
        working-directory: ./hardhat

      - run: npm run deploy:mumbai
        working-directory: ./hardhat

      - run: npm run deploy:emerald-test
        working-directory: ./hardhat

      - run: |
          npm install
          npm run build
        working-directory: ./app
