name: backend_deploy
on:
  push:
    branches:
      - main

env:
  PRIVATE_KEY_MUMBAI: ${{ secrets.PRIVATE_KEY_MUMBAI }}
  PRIVATE_KEY_OASIS: ${{ secrets.PRIVATE_KEY_OASIS }}

concurrency: main

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g npm@8.3.1
      - run: npm -v

      - run: rm -rf ./app/src/generated
      - run: mkdir ./app/src/generated

      - run: npm install
        working-directory: ./hardhat

      - run: npm run test
        working-directory: ./hardhat

      - run: npm run deploy:mumbai
        working-directory: ./hardhat

      - run: npm run deploy:emerald-test
        working-directory: ./hardhat

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: '** --force'
          cwd: './app/src/generated'

      - run: |
          npm install
          npm run build
        working-directory: ./app
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./app
